[ダミー実装] usecases, domain/feature/feature_interactor の実装
dondakeshimo/system-trading pull request #12
Opened 2021-06-27 09:02 UTC by dondakeshimo

## チケット
#4 

## 概要
usecases層と feature_interactorを実装しました。
usecases層はdomain層を実際に用いて処理の手順を記述する部分です。
ただし、全ての手順をusecases層に委ねてしまうとusecase層がfatになってしまうので、ややこしくなりそうかつ、domain/featureに閉じている部分の手順はdomain層に回しました。
該当処理手順はFeatureInteractorに記述しています。
`usecase/find_stocks_to_buy` からは `FeatureInteractor` `BudgetAdjuster` `CodeSelector` を参照することになります。
FeatureInteractorも必要そうであればFactoryを実装することを検討した方が良いかもしれませんが、今の所手順は一つで十分かと思うので、必要となったタイミングで実装します。

## 目的
usecase層までの実装が完了する

### やったこと
- [ ] `usecases/find_stocks_to_buy`
- [ ] `domain/feature/feature_interactor`

### 気になる点・見て欲しいポイント
`find_stocks_to_buy` ってどうなんだ？
価格も提示して買うのに適した株式を見つけ出すという感じの操作だと思うんだけど、端的な英語が分からない。

### TODO
残りはコマンドラインから呼び出す部分とロガー周りの整備

### 参考
見て欲しい外部情報があれば記載

2021-06-27 09:06 UTC, dondakeshimo commented
@Masa-kuchii @IkuyaYamada 
実装完了いたしました。レビューお願いいたします。

TODOが大量でめちゃくちゃ手抜きになっています。
実際に処理を実装するときになんとかすればええやろの精神で書いているのでご容赦願います。

2021-08-01 10:42 UTC, Masa-kuchii commented
#14 クラス名の変更を反映したほうが良いと思うけど、どうだろう？

2021-08-01 11:52 UTC, dondakeshimo commented
@Masa-kuchii 
branch設定二つくらい入れ損なっていたみたいです。
必ずmasterを最新の状態にしてからPRはマージするようにするので、クラス名の反映は必要になります。
今回の場合usecaseのimport文でコケるようになっていますが、conflict自体はないからマージはできてしまいます。
github actionsのcheckは通らないはずなのでmasterを最新にして適切な修正をした後に再度pushする必要があります。

(ちなみに、レビューが多いと修正自体は終わっているのにmasterをひたすらマージし続けなくてはならないという地獄が待っているので速やかなレビューは大事です。)

2021-08-01 16:26 UTC, Masa-kuchii commented on tests/s_tests/domain/strategy/code_selection/test_nonzero_selector.py
> +import pandas as pd
ファイル名（test_nonzero_selector)とテストの中身（DoNothingSelector）が違うかなと！

2021-08-01 16:29 UTC, Masa-kuchii commented on tests/s_tests/domain/strategy/code_selection/test_do_nothing_selector.py
> +import pandas as pd
ファイル名（test_do_nothing_selector)とテストの中身（TopNSelector）が違うと思います！
TopNSelectorのテストはあるので、nonzero_selectorのテスト実装が必要かなと！

2021-08-02 05:19 UTC, dondakeshimo commented on tests/s_tests/domain/strategy/code_selection/test_do_nothing_selector.py
> +import pandas as pd
修正します！

2021-08-02 13:39 UTC, dondakeshimo commented on tests/s_tests/domain/strategy/code_selection/test_do_nothing_selector.py
> +import pandas as pd
@Masa-kuchii 修正しました！

2021-08-03 12:00 UTC, Masa-kuchii commented
@dondakeshimo 
workflowのlintでエラーはいてるけど、これは無視してOK?

2021-08-03 17:27 UTC, Masa-kuchii requested changes
実装ありがとうございます．
細かい点でいくつかコメント残しましたが，
interface，usecaseのロジックともに問題ないと思います！

nonzero_selectorのテスト実装だけお願いします！

2021-08-03 17:27 UTC, Masa-kuchii commented on systrad/usecases/find_stocks_to_buy.py
> +class FindstocksToBuyService:
Findの次のstocksは大文字でしょうか？

クラス名が動詞で始まっている，findだけでなく指示も出しているという点で違和感はありますが，意味通じるので，私は問題ないと思います．もし変更するなら，代替案として，DecidestocksToBuy，StocksToBuyはいかがでしょうか．

2021-08-04 12:05 UTC, dondakeshimo commented on systrad/usecases/find_stocks_to_buy.py
> +        # IDEA: chains of responsibilityでメソッドチェーンにしても良い (結構改修は必要)
strategyで行うべき処理を

```python
.do(nonzero_selector)
.do(budget_adjuster)
.do(top_n_selector)
```

みたいに担当者を繋いでいくパターンっす！

2021-08-04 12:08 UTC, dondakeshimo commented on systrad/usecases/find_stocks_to_buy.py
> +class FindstocksToBuyService:
> Findの次のstocksは大文字でしょうか？

ですね。修正します。

クラス名が動詞始まりなのは意図したものなります。
usecasesに含まれるモジュールは全て実態を持たないサービスオブジェクト(処理を記述したおぶじぇくと)になります。ユースケースにおける処理とは動詞的な行為を指すはずなので、usecase層のモジュール名は(ほとんど)全て動詞始まりで良いかなと考えています。

2021-08-04 12:09 UTC, dondakeshimo commented
@Masa-kuchii 
修正完了しました。ご確認お願いいたします。

2021-08-04 14:56 UTC, Masa-kuchii reviewed
修正ありがとう！
テスト部分問題ないです！

chains of responsibilityのとこだけ、もう少し教えてください～

2021-08-04 14:56 UTC, Masa-kuchii commented on systrad/usecases/find_stocks_to_buy.py
> +        # IDEA: chains of responsibilityでメソッドチェーンにしても良い (結構改修は必要)
説明ありがとう～

確かに、処理の流れとして以下2パターンあるのか。

`code_selector（top_N_selector） →　budget_adjuster`
` budget_adjuster → code_selector（Non_zero_selector)`

これを柔軟に表現しようと思うと、chains of responsibilityしかないのか？

2021-08-06 14:59 UTC, dondakeshimo commented on systrad/usecases/find_stocks_to_buy.py
> +        # IDEA: chains of responsibilityでメソッドチェーンにしても良い (結構改修は必要)
しか無いわけでは全然ない！
色々やり方はあると思うし、もっと依存性なくしたければ設定ファイルとかにクラス名だけ書いておくとかも可能やと思う。
現状は処理順を全部usecases層に書いているけど柔軟性をもたせたほうが良いのだろうかと言う悩みだな。
テストとかをめっちゃ回すとかじゃなければこのままで変更があれば逐一コード修正で大丈夫やと思う！

2021-08-07 08:13 UTC, Masa-kuchii commented on systrad/usecases/find_stocks_to_buy.py
> +        # IDEA: chains of responsibilityでメソッドチェーンにしても良い (結構改修は必要)
了解です！説明ありがとう！

2021-08-07 08:14 UTC, Masa-kuchii commented
問題ないと思うので、マージお願いします！

2021-08-07 11:39 UTC, dondakeshimo commented
@Masa-kuchii 
approveお願いします〜

2021-08-07 12:14 UTC, Masa-kuchii approved these changes
ソリー！お願いします！

2021-08-07 12:26 UTC, merged